name: SonarQube SAST Scan

on:
  push:
     branches: [ "master", "main" ]
#  pull_request:
#    branches: [ "master", "main" ]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: self-hosted   # use your self-hosted runner

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Unit Tests (optional but recommended)
        run: pytest --maxfail=5 --disable-warnings -q

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-python-project \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://192.168.58.13:9000 \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.python.version=3.8 \
            -Dsonar.coverageReportPaths=coverage.xml
